### PR TITLE
updated version to upload

### PR DESCRIPTION
**Pull request by Soto92**
Updated the version to upload.

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
Thanks @Soto92 ! It's now published to npm. 🚀

**Comment by jonatasnardi** [comment]
@Soto92 After this publish, I had problems with my android version... When I type on my TextInput, the content is being replaced with a empty value, then the user is not able to type on the TextInput :(

**Comment by Soto92** [comment]
I will check this problem today. Thank you for letting me know

Em ter, 17 de dez de 2019 00:59, Jonatas Nardi <notifications@github.com>
escreveu:

**Comment by Soto92** [comment]
PR:
https://github.com/nikolaiwarner/react-native-text-input-reset/pull/11

Em ter., 17 de dez. de 2019 às 07:28, Mauricio Andres Soto Pezoa <
mauriciosoto@rede.ulbra.br> escreveu:

**Pull request merged**
